// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXz75qsZs80_ovjVOKvOvIrsl5lrW5Ry4',
    appId: '1:927523194955:web:a6375112a9eac30e6565ce',
    messagingSenderId: '927523194955',
    projectId: 'wallcraft-notification',
    authDomain: 'wallcraft-notification.firebaseapp.com',
    storageBucket: 'wallcraft-notification.firebasestorage.app',
    measurementId: 'G-07Q06JC6R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoocmPO4tJhh9PB_WDZx5mqIJmQwQVxLo',
    appId: '1:927523194955:android:e7cf0e4bc2377ca26565ce',
    messagingSenderId: '927523194955',
    projectId: 'wallcraft-notification',
    storageBucket: 'wallcraft-notification.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS8TtLHDZ2D3k1_ReG9ei-JVg6Tj6PUPE',
    appId: '1:927523194955:ios:be51494320f3464d6565ce',
    messagingSenderId: '927523194955',
    projectId: 'wallcraft-notification',
    storageBucket: 'wallcraft-notification.firebasestorage.app',
    iosBundleId: 'com.wallcraft.app.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS8TtLHDZ2D3k1_ReG9ei-JVg6Tj6PUPE',
    appId: '1:927523194955:ios:be51494320f3464d6565ce',
    messagingSenderId: '927523194955',
    projectId: 'wallcraft-notification',
    storageBucket: 'wallcraft-notification.firebasestorage.app',
    iosBundleId: 'com.wallcraft.app.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXz75qsZs80_ovjVOKvOvIrsl5lrW5Ry4',
    appId: '1:927523194955:web:3de3416c72ffe84c6565ce',
    messagingSenderId: '927523194955',
    projectId: 'wallcraft-notification',
    authDomain: 'wallcraft-notification.firebaseapp.com',
    storageBucket: 'wallcraft-notification.firebasestorage.app',
    measurementId: 'G-21F2YRM21P',
  );
}
